# Generated by Django 4.1.7 on 2023-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=250, null=True)),
                ('recipe', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
