# Generated by Django 4.1.7 on 2023-03-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
